# Generated by Django 3.2.8 on 2021-10-31 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogentry_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('response', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.blogentry')),
            ],
        ),
    ]
